apiVersion: 1

datasources:
  - name: Portal PostgreSQL
    type: postgres
    access: proxy
    uid: portal-postgres-ds
    url: postgres:5432
    user: portal
    database: portal_db
    isDefault: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $GF_DATABASE_PASSWORD