apiVersion: 1

deleteDatasources:
  - name: Portal PostgreSQL
    orgId: 1

datasources:
  - name: Portal PostgreSQL
    type: postgres
    access: proxy
    uid: portal-postgres-ds
    url: postgres:5432
    user: portal
    database: nocodb
    isDefault: true
    jsonData:
      sslmode: disable
      database: nocodb
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: $GF_DATABASE_PASSWORD