# Edition
edition = "2024"

# Line width
max_width = 100
comment_width = 80

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Formatting
use_small_heuristics = "Default"
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80

# Trailing
trailing_comma = "Vertical"
trailing_semicolon = true

# Other
use_field_init_shorthand = true
force_explicit_abi = true